[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "writersroom"
version = "0.1.0"
description = "WritersRoom"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ollama>=0.6.0",
    "pypdf>=6.0.0",
    "python-docx>=1.2.0",
    "streamlit>=1.60.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
